Influxdb udp-client usage support added
olegfedoseev/pinba-influxdb pull request #1
Opened 2018-02-08 07:33 UTC by mguryanov

2018-03-01 07:17 UTC, olegfedoseev requested changes

2018-03-01 07:17 UTC, olegfedoseev commented on config.yml.example
> +# Udp usage:
Why it's after block, and not with http usage example? 
For me, it makes more sense to put it together as a comment for `addr` field.

2018-03-01 07:17 UTC, olegfedoseev commented on main.go
> +	} else {
`else` is redundant, because we have `return`

2018-03-01 07:17 UTC, olegfedoseev commented on main.go
> +}
What is the point of this interface if we not using it? Why not return concrete struct type?

2018-03-01 08:13 UTC, mguryanov commented on config.yml.example
> +# Udp usage:
udp usage has slightly different config requirements
fields like user, password and database not required
that is why this emphasized in separate block

2018-03-01 08:18 UTC, mguryanov commented on main.go
> +	} else {
yes, you are right
i will fix it

2018-03-01 08:32 UTC, mguryanov commented on main.go
> +}
i think it's design matter - introducing some cheap abstraction for simplify main flow understanding
and we using this interface in function
```
func newInfluxdbClient(cfg *config, userAgent string) (influxdbClient, error)
```

2018-03-02 06:45 UTC, olegfedoseev commented
Let's split changes into two PRs - one for UDP client, I'll merge it, and one with "packaging", and here I have doubts. I'm not sure I want Arch specific Dockerfile and PKGBUILD in here.

2018-03-02 08:17 UTC, olegfedoseev commented on main.go
> +}
It has to have some goal, like testability or reusability or at least readability.
Here I see none of the above.
And if you want to use interface, why not original one https://github.com/influxdata/influxdb/blob/master/client/v2/client.go#L66

2018-03-02 09:30 UTC, mguryanov commented on main.go
> +}
Ok!
using original interface :)
I'm will create new PR from udp-client branch, where fixed it

2018-03-05 06:40 UTC, closed without merging